# Generated by Django 4.1.7 on 2023-05-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='achevé',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=3),
        ),
    ]
